version: '3.4'

services:

  northwind:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - InPortDatabase="Server=data.sql;Database=InPortTraders;Trusted_Connection=True;Application Name=InPort;User Id=sa;Password=Pass@word"
      - EventSourcingDatabase="Server=data.sql;Database=InPortTradersEventSourcing;Trusted_Connection=True;Application Name=InPort;User Id=sa;Password=Pass@word"
 
    ports:
      - "81:80"

  data.sql:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"    # Important: In a production environment your should remove the external port