version: '3.4'

services:

  northwind:
    image: northwind:latest
    build:
      context: .
      dockerfile: Northwind.WebUI/Dockerfile
    depends_on:
      - data.sql

  data.sql:
    image: microsoft/mssql-server-linux:2017-latest